### ISSUE TITLE
unable to clone and npm install. + instagram linking issue

### ISSUE THREAD

**Issue by davronakil** [oftheheadland/SocialSnapper#2]
Firstly, my issue is that i'm getting this error trying to run `npm install`:

```
npm WARN react-fade-in@0.1.6 requires a peer of react@^15.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.0.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.

updated 3 packages and audited 37693 packages in 18.299s
found 91 vulnerabilities (63 low, 11 moderate, 17 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

I wanted to clone to submit an update for the new instagram link structure, new links like `https://www.instagram.com/donnyarcade/p/BwxjIsEDnWj/` do not get recognized (until you edit it to be `https://www.instagram.com/p/BwxjIsEDnWj/` (throws this error: `Error with your search. Please use an instagram post or story URL`

**Comment by davronakil** [comment]
Was able to fix my issue with `npm audit fix --force`, but the issue with the instagram link remains.

**Comment by oftheheadland** [comment]
Looking into this, thanks for bringing it to my attention.

**Comment by davronakil** [comment]
In `/src/components/Instagram.js` on line 56, I added this: 

```
 // correct links like https://www.instagram.com/donnyarcade/p/BwxjIsEDnWj/ to be ...com/p/...
      let firstString = cleanInstagramURL.split('/')[3];

      if (firstString !== "p") {
        cleanInstagramURL = cleanInstagramURL.replace("/"+firstString, "");
      }
```

here's a JSFiddle to test it and it's working: https://jsfiddle.net/8p75m9ue/


However, I'm unable to get the app to accept it locally. Hmm 🤔.

**Comment by oftheheadland** [comment]
@davronakil Thank you for your interest in contributing. I would not have noticed this problem without you. the fix had to be made on my flask server. Should be working now, would you mind verifying that for me?

https://www.instagram.com/donnyarcade/p/BwxjIsEDnWj/ 
https://www.instagram.com/p/BwxjIsEDnWj/

**Comment by davronakil** [comment]
Yep. Working now! Good stuff. 
And you're very welcome. Thanks for this great tool.

**Comment by oftheheadland** [comment]
Happy to provide it. 😄

**Comment by davronakil** [comment]
Can we adjust again to work with the new URL structure like 'https://www.instagram.com/tv/B0XP14kFevt/?igshid=t7elvcpn688r'?

**Comment by oftheheadland** [comment]
Fixed, /tv/ subdomain works now :)
